name: Publish detekt rules package to GitHub Packages
on:
  release:
    types: [ created ]
  workflow_dispatch:
env:
  GITHUB_TOKEN_PUBLISH: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch tags
        run: git fetch --tags --unshallow
      - uses: ./.github/actions/setup
      - name: Release version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :release \
          -Prelease.customUsername=${{ github.actor }} \
          -Prelease.customPassword=${{ github.token }}
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :publish
